CREATE DATABASE Academia_jj;

USE Academia_jj;

CREATE TABLE ESPECIALIDADE(
    CodEspecialidade INT UNSIGNED AUTO_INCREMENT,
    NomeEspecialidade VARCHAR(100) NOT NULL,
    Status CHAR(1) DEFAULT 'A',
    PRIMARY KEY(CodEspecialidade)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE INSTRUTOR(
    CodInstrutor INT UNSIGNED AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    HorarioDisponivel VARCHAR(100),
    status CHAR(1) DEFAULT 'A',
    FkCodEspecialidade INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodInstrutor) 
   )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO(
    CodUsuario INT UNSIGNED AUTO_INCREMENT, 
    Nome VARCHAR(100) NOT NULL,
    DataDeNasc DATE NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Senha VARCHAR(50) NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    Genero VARCHAR(10) NOT NULL,
    Peso DECIMAL(3,2) DEFAULT 000.00,
    Altura DECIMAL(2,2) DEFAULT 00.00,
    ProblemasDeSaude TEXT,
    TipoUsuario VARCHAR(20),
    Status CHAR(1) DEFAULT 'A',
    FkCodMatricula INT UNSIGNED NOT NULL,
    FkCodInstrutor INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodUsuario)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALUNO(
    CodAluno INT UNSIGNED AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    DataInicio DATE NOT NULL,
    Observacoes VARCHAR(255),
    Status CHAR(1) DEFAULT 'A',
    StatusDePagamentos CHAR(1) DEFAULT 'A',
    NivelCondicionamento VARCHAR(50),
    ObjetivoTreino VARCHAR(255),
    AvaliacaoFisica VARCHAR(255),
    UltimaAtualizacao VARCHAR(100),
    FkCodUsuario INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodAluno)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MATRICULA(
    CodMatricula INT UNSIGNED AUTO_INCREMENT,
    DataDeMatricula DATE NOT NULL,
    DuracaoContrato VARCHAR(50),
    ValorContrato DECIMAL(10,2) DEFAULT 000.00,
    Status CHAR(1) DEFAULT 'A',
    FkCodAluno INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodMatricula)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PAGAMENTO(
    CodPagamento INT UNSIGNED AUTO_INCREMENT,
    TipoPagamento VARCHAR(50),
    Valor DECIMAL(10,2) NOT NULL DEFAULT 000.00,
    DataVencimento DATE NOT NULL,
    DataPagamento DATE,
    Status CHAR(1) DEFAULT 'N',
    FkCodAluno INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodPagamento)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TURMA(
    CodTurma INT UNSIGNED AUTO_INCREMENT,
	NomeTurma VARCHAR(100) NOT NULL,
    Descricao VARCHAR(255),
    LimiteAlunos INT,
    Local VARCHAR(100) NOT NULL,
    DataInicio DATE NOT NULL,
    DataTermino DATE NOT NULL,
    Status CHAR(1) DEFAULT 'A',
    FkCodEspecialidade INT UNSIGNED NOT NULL,
    FKCodInstrutor INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodTurma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ENDERECO(
    CodEndereco INT UNSIGNED AUTO_INCREMENT,
    Rua VARCHAR(100) NOT NULL,
    Numero INT NOT NULL,
    Complemento VARCHAR(100),
    Bairro VARCHAR(100),
    Cidade VARCHAR(100),
    Cep INT NOT NULL,
    status CHAR(1) DEFAULT 'A',
    FkCodUsuario INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodEndereco)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PIX(
    CodPix INT UNSIGNED AUTO_INCREMENT,
    ChavePix VARCHAR(100) NOT NULL,
    Valor DECIMAL(10,2) NOT NULL,
    DataCriacao DATETIME,
    DataTransacao DATETIME,
    Status CHAR(1) DEFAULT 'P',
    FkCodPagamento INT UNSIGNED NOT NULL,
    FkCodAluno INT UNSIGNED NOT NULL,
    PRIMARY KEY(CodPix) 
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE HORARIO(
    CodHorario INT UNSIGNED AUTO_INCREMENT,
    DiadaSemana VARCHAR(15) NOT NULL,
    HoraInicio TIME NOT NULL,
    HoraTerminio TIME NOT NULL,
    FkCodTurma INT UNSIGNED NOT NULL,
	PRIMARY KEY(CodHorario)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE USUARIO ADD CONSTRAINT FK_Usuario_Matricula FOREIGN KEY (FkCodMatricula) REFERENCES MATRICULA (CodMatricula);
ALTER TABLE USUARIO ADD CONSTRAINT FK_Usuario_Instrutor FOREIGN KEY (FkCodInstrutor) REFERENCES INSTRUTOR(CodInstrutor);
ALTER TABLE TURMA ADD CONSTRAINT FK_Turma_Instrutor FOREIGN KEY (FkCodInstrutor) REFERENCES INSTRUTOR(CodInstrutor);
ALTER TABLE TURMA ADD CONSTRAINT FK_Turma_Especialidade FOREIGN KEY (FkCodEspecialidade) REFERENCES Especialidade(CodEspecialidade);
ALTER TABLE MATRICULA ADD CONSTRAINT FK_Matricula_Aluno FOREIGN KEY (FkCodAluno) REFERENCES ALUNO(CodAluno);
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_Pagamento_Aluno FOREIGN KEY (FkCodAluno) REFERENCES ALUNO(CodAluno);
ALTER TABLE ENDERECO ADD CONSTRAINT FK_Endereco_Usuario FOREIGN KEY (FkCodUsuario) REFERENCES USUARIO(CodUsuario);
ALTER TABLE PIX ADD CONSTRAINT FK_PIX_Aluno FOREIGN KEY (FkCodAluno) REFERENCES ALUNO(CodAluno);
ALTER TABLE PIX ADD CONSTRAINT FK_PIX_Pagamento FOREIGN KEY (FkCodPagamento) REFERENCES PAGAMENTO(CodPagamento);
ALTER TABLE HORARIO ADD CONSTRAINT FK_Horario_Turma FOREIGN KEY (FkCodTurma) REFERENCES TURMA(CodTurma);


